### ISSUE TITLE
Chamfer m3 nut holes to fix elephant's foot

### ISSUE THREAD

**Issue by BenRinthLabs** [opulo-inc/lumenpnp#629] opened 2022-11-08 03:53 UTC
![PXL_20221107_220029310_2](https://user-images.githubusercontent.com/25337335/200470949-bfb9f187-b5ae-4d62-bce6-1e3d46ff2c24.jpg)

The elephant's foot on the first layer is preventing the m3 nuts from being inserted easily. I used a knife to trim off the elephant's foot which worked, but it'd be great if the first layer or two were chamfered so printers that aren't 100% fine tuned can still make working parts off the print bed with no post processing.

**Comment by sphawes** [comment] 2023-05-15 17:57
Thank you for the note @CurlyTaleGames! I totally hear ya, it can be hard to get them seated sometimes. We've actually found that having the elephant's foot helps hold the nut _in_ a little better if a printer is slightly undersizing parts. The downside is that some voids can often require an arbor press or something similar to get the nut in place.

There's a lot of stuff in the machine that is press-fit by design, and needs to stay put for shipping. I'm hesitant to remove the default geometry (especially because most printers nowadays can pretty easily eliminate elephant's foot) because it is some added insurance that nuts stay put during shipping.

I'm going to close this for now, but I've talked to Lucian about this and we'll consider adding these on tight pockets in the future!

**Closed as completed by sphawes** 2023-05-15 17:57 UTC
Labels: area: cad, project: lumen
